# https://github.com/alexey-goloburdin/botanim-bot/blob/main/.github/workflows/lint_and_types.yml
name: Lint and check types

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
  
    - name: Install poetry
      run: |
        pip install pipx
        pipx install poetry

    - name: Validate the structure of the pyproject.toml
      run: |
        poetry check

    - name: Verify that poetry.lock is consistent with pyproject.toml
      run: |
        poetry lock --check
    
    - name: Install dependencies
      run: |
        poetry install
    
    - name: Lint code by ruff
      if: success() || failure()
      run: |
        poetry run ruff .
        
    - name: Check types by pyright
      if: success() || failure()
      run: |
        poetry run pyright

    - name: Check code formatting by black
      if: success() || failure()
      run: |
        poetry run black . --check
    